### ISSUE TITLE
Map NIST/FIPS and remove from this repo

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-misc#8]
[reference.FIPS.1-1.1980.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.1-1.1980.xml)
[reference.FIPS.113.1985.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.113.1985.xml)
[reference.FIPS.146-1.1989.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.146-1.1989.xml)
[reference.FIPS.146-1.1991.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.146-1.1991.xml)
[reference.FIPS.146.1988.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.146.1988.xml)
[reference.FIPS.146.1990.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.146.1990.xml)
[reference.FIPS.161-1.1993.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.161-1.1993.xml)
[reference.FIPS.180-1.1994.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.180-1.1994.xml)
[reference.FIPS.180-1.1995.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.180-1.1995.xml)
[reference.FIPS.180-2.2002.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.180-2.2002.xml)
[reference.FIPS.180.1993.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.180.1993.xml)
[reference.FIPS.186-1.1998.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.186-1.1998.xml)
[reference.FIPS.186.1994.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.186.1994.xml)
[reference.FIPS.197.2001.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.197.2001.xml)
[reference.FIPS.35.1975.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.35.1975.xml)
[reference.FIPS.4.1968.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.4.1968.xml)
[reference.FIPS.46-1.1988.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.46-1.1988.xml)
[reference.FIPS.46-2.1993.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.46-2.1993.xml)
[reference.FIPS.46.1977.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.46.1977.xml)
[reference.FIPS.5-2.1987.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.5-2.1987.xml)
[reference.FIPS.500-166.1989.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.500-166.1989.xml)
[reference.FIPS.500-20.1977.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.500-20.1977.xml)
[reference.FIPS.500-61.1980.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.500-61.1980.xml)
[reference.FIPS.55-2.1987.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.55-2.1987.xml)
[reference.FIPS.58.1979.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.58.1979.xml)
[reference.FIPS.59.1979.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.59.1979.xml)
[reference.FIPS.6-4.1990.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.6-4.1990.xml)
[reference.FIPS.74.1981.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.74.1981.xml)
[reference.FIPS.81.1980.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.81.1980.xml)
[reference.FIPS.95-1.1993.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.95-1.1993.xml)
[reference.FIPS.98.1983.xml](https://www.rfc-editor.org/refs/bibxml2/reference.FIPS.98.1983.xml)
[reference.NIST.500-162.1988.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-162.1988.xml)
[reference.NIST.500-162.1990.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-162.1990.xml)
[reference.NIST.500-163.1989.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-163.1989.xml)
[reference.NIST.500-166.1989.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-166.1989.xml)
[reference.NIST.500-183.1990.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-183.1990.xml)
[reference.NIST.500-20.1977.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-20.1977.xml)
[reference.NIST.500-214.1993.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-214.1993.xml)
[reference.NIST.500-61.1980.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.500-61.1980.xml)
[reference.NIST.FIPS.202.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.FIPS.202.xml)
[reference.NIST.SP.800-185.xml](https://www.rfc-editor.org/refs/bibxml2/reference.NIST.SP.800-185.xml)

**Comment by ronaldtse** [comment]
[mapping.yaml.zip](https://github.com/ietf-tools/relaton-data-misc/files/9019925/mapping.yaml.zip)

I was able to map these entries, but there are a number of them that are not available from the official NIST database. 

```yaml
---
reference.FIPS.1-1.1980.xml: NBS FIPS 1
reference.FIPS.113.1985.xml: NBS FIPS 113
reference.FIPS.146-1.1989.xml
reference.FIPS.146-1.1991.xml: NIST FIPS 146-1
reference.FIPS.146.1988.xml
reference.FIPS.146.1990.xml
reference.FIPS.161-1.1993.xml
reference.FIPS.180-1.1994.xml: NIST FIPS 180-1
reference.FIPS.180-1.1995.xml
reference.FIPS.180-2.2002.xml
reference.FIPS.180.1993.xml: NIST FIPS 180
reference.FIPS.186-1.1998.xml
reference.FIPS.186.1994.xml
reference.FIPS.197.2001.xml: NIST FIPS 197
reference.FIPS.35.1975.xml: NBS FIPS 35
reference.FIPS.4.1968.xml
reference.FIPS.46-1.1988.xml
reference.FIPS.46-2.1993.xml: NIST FIPS 46-2
reference.FIPS.46.1977.xml: NIST FIPS 46 (but this is 1990)
reference.FIPS.5-2.1987.xml: NBS FIPS 5-2
reference.FIPS.500-166.1989.xml: NBS SP 500-116 (but this is 1984)
reference.FIPS.500-20.1977.xml
reference.FIPS.500-61.1980.xml: NBS SP 500-61
reference.FIPS.55-2.1987.xml
reference.FIPS.58.1979.xml: NBS FIPS 58-1979
reference.FIPS.59.1979.xml: NBS FIPS 59
reference.FIPS.6-4.1990.xml: NIST FIPS 6-4
reference.FIPS.74.1981.xml: NBS FIPS 74
reference.FIPS.81.1980.xml: NBS FIPS 81
reference.FIPS.95-1.1993.xml: NBS FIPS 95-1
reference.FIPS.98.1983.xml: NBS FIPS 98
reference.NIST.500-162.1988.xml: NIST SP 500-162 (but this is 1989)
reference.NIST.500-162.1990.xml
reference.NIST.500-163.1989.xml: NIST SP 500-163
reference.NIST.500-166.1989.xml: NIST SP 500-166
reference.NIST.500-183.1990.xml: NIST SP 500-183 (but this is 1991)
reference.NIST.500-20.1977.xml: NBS SP 500-61 (but this is 1980)
reference.NIST.500-214.1993.xml
reference.NIST.500-61.1980.xml
reference.NIST.FIPS.202.xml: NIST FIPS 202
reference.NIST.SP.800-185.xml: NIST SP 800-185
```

Also posted to https://github.com/relaton/relaton-data-nist/issues/6

**Comment by ronaldtse** [comment]
As per https://github.com/relaton/relaton-data-nist/issues/6#issuecomment-1171453451 .

The resulting YAML mapping file is below:
```yaml
---
reference.FIPS.1-1.1980.xml: NBS FIPS 1
reference.FIPS.113.1985.xml: NBS FIPS 113
reference.FIPS.146-1.1989.xml: fallback_unless_available(NIST FIPS 146)
reference.FIPS.146-1.1991.xml: NIST FIPS 146-1
reference.FIPS.146.1988.xml: fallback_unless_available(NIST FIPS 146)
reference.FIPS.146.1990.xml: NIST FIPS 146-1
reference.FIPS.161-1.1993.xml: fallback_unless_available(NIST FIPS 161-1)
reference.FIPS.180-1.1994.xml: NIST FIPS 180-1
reference.FIPS.180-1.1995.xml: NIST FIPS 180-1
reference.FIPS.180-2.2002.xml: fallback_unless_available(NIST FIPS 180-2)
reference.FIPS.180.1993.xml: NIST FIPS 180
reference.FIPS.186-1.1998.xml: fallback_unless_available(NIST FIPS 186-1)
reference.FIPS.186.1994.xml: NIST FIPS 186
reference.FIPS.197.2001.xml: NIST FIPS 197
reference.FIPS.35.1975.xml: NBS FIPS 35
reference.FIPS.4.1968.xml: fallback_unless_available(NBS FIPS 4)
reference.FIPS.46-1.1988.xml: fallback_unless_available(NBS 46-1)
reference.FIPS.46-2.1993.xml: NIST FIPS 46-2
reference.FIPS.46.1977.xml: NIST FIPS 46 (but this is 1990)
reference.FIPS.5-2.1987.xml: NBS FIPS 5-2
reference.FIPS.500-166.1989.xml: NBS SP 500-116 (but this is 1984)
reference.FIPS.500-20.1977.xml: fallback_unless_available(NBS SP 500-20)
reference.FIPS.500-61.1980.xml: NBS SP 500-61
reference.FIPS.55-2.1987.xml: fallback_unless_available(NBS FIPS 55-2)
reference.FIPS.58.1979.xml: NBS FIPS 58-1979
reference.FIPS.59.1979.xml: NBS FIPS 59
reference.FIPS.6-4.1990.xml: NIST FIPS 6-4
reference.FIPS.74.1981.xml: NBS FIPS 74
reference.FIPS.81.1980.xml: NBS FIPS 81
reference.FIPS.95-1.1993.xml: NBS FIPS 95-1
reference.FIPS.98.1983.xml: NBS FIPS 98
reference.NIST.500-162.1988.xml: NIST SP 500-162
reference.NIST.500-162.1990.xml: NIST SP 500-162
reference.NIST.500-163.1989.xml: NIST SP 500-163
reference.NIST.500-166.1989.xml: NIST SP 500-166
reference.NIST.500-183.1990.xml: NIST SP 500-183 (but this is 1991)
reference.NIST.500-20.1977.xml: fallback_unless_available(NBS SP 500-20)
reference.NIST.500-214.1993.xml: fallback_unless_available(NIST SP 500-214)
reference.NIST.500-61.1980.xml: NBS SP 500-61
reference.NIST.FIPS.202.xml: NIST FIPS 202
reference.NIST.SP.800-185.xml: NIST SP 800-185
```

The syntax `fallback_unless_available(...)` means that the NIST data set does not have content right now, but when it does have them, the document identifiers provided as `...` will be correct.

[mapping.yaml.zip](https://github.com/relaton/relaton-data-nist/files/9021819/mapping.yaml.zip)
